{% set name = "torchmd" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/torchmd-{{ version }}.tar.gz
  sha256: 30d6898fea4cd53ad92b29834fec168802e3056fb654ca316d50d75daa3060a3

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - versioneer
  run:
    - python >={{ python_min }}
    - pyyaml
    - scipy
    - pytorch
    - torchvision
    - moleculekit
    - networkx
    - pandas
    - tqdm

test:
  imports:
    - torchmd
    - torchmd.forcefields
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://www.torchmd.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: End-To-End Molecular Dynamics (MD) Engine using PyTorch
  description: |
    TorchMD intends to provide a simple to use API for performing
    molecular dynamics using PyTorch. This enables researchers to more
    rapidly do research in force-field development as well as integrate
    seamlessly neural network potentials into the dynamics, with the
    simplicity and power of PyTorch.
  doc_url: http://www.torchmd.org/
  dev_url: https://github.com/torchmd/torchmd/

extra:
  recipe-maintainers:
    - jan-janssen
